set_property PACKAGE_PIN Y18 [get_ports pwm_interrupt]
set_property PACKAGE_PIN Y19 [get_ports pwm_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_interrupt]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTN[0]}]
set_property PACKAGE_PIN U18 [get_ports {BTN[0]}]
set_property PACKAGE_PIN U19 [get_ports {BTN[1]}]
set_property PACKAGE_PIN W18 [get_ports {BTN[2]}]
set_property PACKAGE_PIN W19 [get_ports {BTN[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LCD_cmd_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_cmd_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_D_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_D_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_D_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_D_out[0]}]

set_property -dict { PACKAGE_PIN K9    IOSTANDARD LVCMOS33 } [get_ports { v_p }]; #VP_0 Sch=xadc_v_p
set_property -dict { PACKAGE_PIN L10   IOSTANDARD LVCMOS33 } [get_ports { v_n }]; #VN_0 Sch=xadc_v_n

set_property -dict { PACKAGE_PIN E17   IOSTANDARD LVCMOS33 } [get_ports { vaux1_p }]; #IO_L3P_T0_DQS_AD1P_35 Sch=ck_an_p[0]
set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { vaux1_n }]; #IO_L3N_T0_DQS_AD1N_35 Sch=ck_an_n[0]

set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS33 } [get_ports { vaux9_p }]; #IO_L5P_T0_AD9P_35 Sch=ck_an_p[1]
set_property -dict { PACKAGE_PIN E19   IOSTANDARD LVCMOS33 } [get_ports { vaux9_n }]; #IO_L5N_T0_AD9N_35 Sch=ck_an_n[1]

set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux9_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux9_0_v_p]

set_property PACKAGE_PIN U14 [get_ports {LCD_D_out[3]}]
set_property PACKAGE_PIN V13 [get_ports {LCD_D_out[2]}]
set_property PACKAGE_PIN T14 [get_ports {LCD_D_out[1]}]
set_property PACKAGE_PIN T15 [get_ports {LCD_D_out[0]}]
set_property PACKAGE_PIN R16 [get_ports {LCD_cmd_out[1]}]
set_property PACKAGE_PIN U12 [get_ports {LCD_cmd_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_lcd_6bits_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_lcd_6bits_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_lcd_6bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_lcd_6bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_lcd_6bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_lcd_6bits_tri_o[0]}]
set_property PACKAGE_PIN V13 [get_ports {gpio_lcd_6bits_tri_o[2]}]
set_property PACKAGE_PIN T14 [get_ports {gpio_lcd_6bits_tri_o[1]}]
set_property PACKAGE_PIN T15 [get_ports {gpio_lcd_6bits_tri_o[0]}]
set_property PACKAGE_PIN U14 [get_ports {gpio_lcd_6bits_tri_o[3]}]
set_property PACKAGE_PIN U12 [get_ports {gpio_lcd_6bits_tri_o[4]}]
set_property PACKAGE_PIN R16 [get_ports {gpio_lcd_6bits_tri_o[5]}]

